// Auto-generated by scripts/bundle-quran.mjs
// Do not edit manually. Run `npm run bundle-quran` to regenerate.

export interface BundledVerse {
  id: number;
  verse_key: string;
  text_uthmani: string;
  verse_number: number;
}

import p1 from "./paras/1.json";
import p2 from "./paras/2.json";
import p3 from "./paras/3.json";
import p4 from "./paras/4.json";
import p5 from "./paras/5.json";
import p6 from "./paras/6.json";
import p7 from "./paras/7.json";
import p8 from "./paras/8.json";
import p9 from "./paras/9.json";
import p10 from "./paras/10.json";
import p11 from "./paras/11.json";
import p12 from "./paras/12.json";
import p13 from "./paras/13.json";
import p14 from "./paras/14.json";
import p15 from "./paras/15.json";
import p16 from "./paras/16.json";
import p17 from "./paras/17.json";
import p18 from "./paras/18.json";
import p19 from "./paras/19.json";
import p20 from "./paras/20.json";
import p21 from "./paras/21.json";
import p22 from "./paras/22.json";
import p23 from "./paras/23.json";
import p24 from "./paras/24.json";
import p25 from "./paras/25.json";
import p26 from "./paras/26.json";
import p27 from "./paras/27.json";
import p28 from "./paras/28.json";
import p29 from "./paras/29.json";
import p30 from "./paras/30.json";

const bundledParas: Record<number, BundledVerse[]> = {
  1: p1 as BundledVerse[],
  2: p2 as BundledVerse[],
  3: p3 as BundledVerse[],
  4: p4 as BundledVerse[],
  5: p5 as BundledVerse[],
  6: p6 as BundledVerse[],
  7: p7 as BundledVerse[],
  8: p8 as BundledVerse[],
  9: p9 as BundledVerse[],
  10: p10 as BundledVerse[],
  11: p11 as BundledVerse[],
  12: p12 as BundledVerse[],
  13: p13 as BundledVerse[],
  14: p14 as BundledVerse[],
  15: p15 as BundledVerse[],
  16: p16 as BundledVerse[],
  17: p17 as BundledVerse[],
  18: p18 as BundledVerse[],
  19: p19 as BundledVerse[],
  20: p20 as BundledVerse[],
  21: p21 as BundledVerse[],
  22: p22 as BundledVerse[],
  23: p23 as BundledVerse[],
  24: p24 as BundledVerse[],
  25: p25 as BundledVerse[],
  26: p26 as BundledVerse[],
  27: p27 as BundledVerse[],
  28: p28 as BundledVerse[],
  29: p29 as BundledVerse[],
  30: p30 as BundledVerse[]
};

export default bundledParas;
